"""Command-line entry point for crawling and rendering website link graphs."""

import argparse
from pathlib import Path
from urllib.parse import urlsplit

from crawler import crawl_site, recheck_external, resolve_url
from crawl_result import load_data, summarize, write_json
from render import read_options, visualize


def main():
    parser = argparse.ArgumentParser(description='Visualize the link graph of a website.')
    parser.add_argument('site_url', nargs='?', default='', help='base URL of the website')
    parser.add_argument('--vis-file', default='site.html', help='HTML graph output (default: site.html)')
    parser.add_argument('--json-file', help='JSON output (default: crawl.json for a new crawl; none for saved data)')
    parser.add_argument('--from-data-file', help='render saved JSON without network requests')
    parser.add_argument('--recheck-external', action='store_true', help='check saved external targets again (network)')
    parser.add_argument('--visit-external', action='store_true', help='detect broken external links (slower)')
    parser.add_argument('--workers', type=int, help='parallel external checks (default: 4, or saved setting)')
    parser.add_argument('--keep-queries', action='store_true', help='keep internal query strings; always remove fragments')
    parser.add_argument('--force', action='store_true', help='allow an HTTP base URL instead of HTTPS')
    parser.add_argument('--width', type=int, default=1000, help='graph width in pixels (default: 1000)')
    parser.add_argument('--height', type=int, default=800, help='graph height in pixels (default: 800)')
    parser.add_argument('--show-buttons', action='store_true', help='show visualization settings UI')
    parser.add_argument('--interactive-controls', action='store_true', help='add URL search, filters, legend and neighbor selection')
    parser.add_argument('--options', help='drawing options file generated by the settings UI')
    parser.add_argument('--only-404', action='store_true', help='only color 404 errors red')
    parser.add_argument('--save-txt', nargs='?', const='adj_matrix.txt', help='save adjacency matrix and *_nodes.txt labels')
    parser.add_argument('--save-npz', nargs='?', const='adj_matrix.npz', help='save sparse adjacency matrix and *_nodes.txt labels')
    args = parser.parse_args()

    if args.workers is not None and args.workers < 1:
        parser.error('--workers must be at least 1')
    if args.width < 1 or args.height < 1:
        parser.error('--width and --height must be positive')
    if not args.vis_file.endswith('.html'):
        parser.error('--vis-file must end in .html')
    if args.show_buttons and args.options:
        parser.error('--show-buttons and --options cannot be combined')
    if args.save_txt and args.save_npz:
        parser.error('choose --save-txt or --save-npz, not both')
    if args.recheck_external and not args.from_data_file:
        parser.error('--recheck-external requires --from-data-file')
    if args.from_data_file and (args.site_url or args.visit_external or args.keep_queries):
        parser.error('saved data defines root/scope/query policy; use --recheck-external for network checks')

    if not args.from_data_file and args.json_file is None:
        args.json_file = 'crawl.json'
    if args.save_npz and not args.save_npz.endswith('.npz'):
        args.save_npz += '.npz'
    outputs = [args.vis_file]
    if args.json_file:
        outputs.append(args.json_file)
    matrix_file = args.save_npz or args.save_txt
    if matrix_file:
        matrix = Path(matrix_file)
        outputs += [matrix_file, str(matrix.with_name(matrix.stem + '_nodes.txt'))]
    inputs = [value for value in (args.options, args.from_data_file) if value]
    paths = [Path(value).resolve() for value in outputs + inputs]
    if len(paths) != len(set(paths)):
        parser.error('input and output files must have distinct paths')
    for filename in outputs:
        path = Path(filename)
        if not path.parent.is_dir() or path.is_dir():
            parser.error(f'invalid output path: {filename}')

    try:
        if args.options is not None:
            args.options = read_options(args.options)
        if args.from_data_file:
            result = load_data(args.from_data_file)
            if args.recheck_external:
                result = recheck_external(result, args.workers)
                if args.json_file is None:
                    print('External checks updated in memory only; use --json-file to save them.')
        else:
            site_url = resolve_url(args.site_url)
            if site_url is None:
                parser.error('site_url must be an absolute HTTP or HTTPS URL')
            if urlsplit(site_url).scheme != 'https' and not args.force:
                parser.error('not using https; use --force to allow http')
            result = crawl_site(site_url, args.visit_external, args.keep_queries, args.workers or 4)
        if args.json_file is not None:
            write_json(result, args.json_file)
            print(f'Saved crawl JSON to {args.json_file}')
        print(summarize(result))
        visualize(result, args)
    except (ValueError, OSError) as error:
        parser.exit(1, f'Error: {error}\n')
    print('Saved graph to', args.vis_file)


if __name__ == '__main__':
    main()
